# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "fonttools>=4.59.0",
# ]
# ///

from __future__ import annotations

import json
import math
import re
import struct
import zlib
from pathlib import Path

from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parents[1]
FONT_PATH = ROOT / "fonts/wqy-zenhei-sharp-0.9.45.ttf"
OUT_DIR = ROOT / "public/assets/cjk"
GENERATED = ROOT / "src/generated/cjk-atlas.ts"
CONTENT_ROOTS = ("src/content", "src/config", "src/components", "src/pages")
TEXT_EXTENSIONS = {".astro", ".phile", ".ts"}
PUNCTUATION = "　，。：；、？！（）《》「」『』【】—…￥"
CJK_PATTERN = re.compile(
    r"[\u3000-\u303f\u3400-\u4dbf\u4e00-\u9fff"
    r"\uf900-\ufaff\uff00-\uffef]"
)
CELL_SIZE = 16
COLS = 32
BODY_PPEM = 13
LINK_PPEM = 15


def main() -> None:
    chars = collect_chars()
    font = TTFont(FONT_PATH)
    cmap = best_cmap(font)
    glyphs = {
        char: index
        for index, char in enumerate(char for char in chars if ord(char) in cmap)
    }

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    GENERATED.parent.mkdir(parents=True, exist_ok=True)

    write_atlas(font, glyphs, BODY_PPEM, OUT_DIR / "wqy-cjk-body.png")
    write_atlas(font, glyphs, LINK_PPEM, OUT_DIR / "wqy-cjk-link.png")
    write_generated(glyphs)


def collect_chars() -> list[str]:
    chars = set(PUNCTUATION)

    for root in CONTENT_ROOTS:
        base = ROOT / root

        if not base.exists():
            continue

        for path in base.rglob("*"):
            if path.is_file() and path.suffix in TEXT_EXTENSIONS:
                chars.update(
                    match.group(0)
                    for match in CJK_PATTERN.finditer(path.read_text(encoding="utf8"))
                )

    return sorted(chars, key=lambda char: ord(char))


def write_atlas(font: TTFont, glyphs: dict[str, int], ppem: int, output: Path) -> None:
    strike_index = next(
        index
        for index, strike in enumerate(font["EBLC"].strikes)
        if strike.bitmapSizeTable.ppemY == ppem
    )
    strike = font["EBDT"].strikeData[strike_index]
    cmap = best_cmap(font)
    rows = max(1, math.ceil(len(glyphs) / COLS))
    width = COLS * CELL_SIZE
    height = rows * CELL_SIZE
    pixels = bytearray(width * height * 4)
    baseline = ppem - 1

    for char, index in glyphs.items():
        glyph_name = cmap.get(ord(char))

        if glyph_name is None or glyph_name not in strike:
            continue

        glyph = strike[glyph_name]

        try:
            glyph.ensureDecompiled()
            metrics = glyph.metrics
        except AttributeError:
            continue

        cell_x = (index % COLS) * CELL_SIZE
        cell_y = (index // COLS) * CELL_SIZE
        origin_x = cell_x + max(0, metrics.horiBearingX)
        origin_y = cell_y + max(0, baseline - metrics.horiBearingY)

        for y in range(metrics.height):
            row = glyph.getRow(y, bitDepth=1, metrics=metrics, reverseBytes=True)

            for x in range(metrics.width):
                if not row[x // 8] >> (x % 8) & 1:
                    continue

                px = origin_x + x
                py = origin_y + y

                if 0 <= px < width and 0 <= py < height:
                    offset = (py * width + px) * 4
                    pixels[offset : offset + 4] = b"\xff\xff\xff\xff"

    write_png(output, width, height, pixels)


def best_cmap(font: TTFont) -> dict[int, str]:
    cmap = font.getBestCmap()

    if cmap is None:
        raise ValueError(f"Font has no Unicode cmap: {FONT_PATH}")

    return cmap


def write_png(output: Path, width: int, height: int, pixels: bytearray) -> None:
    def chunk(kind: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + kind
            + data
            + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)
        )

    raw = bytearray()

    for y in range(height):
        raw.append(0)
        start = y * width * 4
        raw.extend(pixels[start : start + width * 4])

    png = (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(bytes(raw), 9))
        + chunk(b"IEND", b"")
    )
    output.write_bytes(png)


def write_generated(glyphs: dict[str, int]) -> None:
    glyph_items = sorted(glyphs.items(), key=lambda item: item[1])
    glyph_lines = []

    for offset, (char, index) in enumerate(glyph_items):
        suffix = "," if offset < len(glyph_items) - 1 else ""
        glyph_lines.append(f"    {json.dumps(char, ensure_ascii=True)}: {index}{suffix}")

    GENERATED.write_text(
        "\n".join(
            [
                "// Generated by scripts/build-cjk-atlas.py.",
                "export const cjkAtlas = {",
                f"  cellSize: {CELL_SIZE},",
                f"  columns: {COLS},",
                "  glyphs: {",
                *glyph_lines,
                "  }",
                "} as const;",
                "",
            ]
        ),
        encoding="utf8",
    )


if __name__ == "__main__":
    main()
